import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:wasd/wasd.dart';

void main() {
  group('WasmComponent.decode', () {
    test('requires componentModel feature', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
      ]);

      expect(
        () => WasmComponent.decode(componentBytes),
        throwsA(isA<UnsupportedError>()),
      );
    });

    test('decodes a minimal component and exposes sections', () {
      // Generated by wasm-tools component encoder from `(module)`.
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.sections, hasLength(2));
      expect(component.coreModules, hasLength(1));
      expect(component.coreInstances, hasLength(1));
      expect(component.coreInstances.single.moduleIndex, 0);
      expect(
        component.coreModules.single,
        orderedEquals(const <int>[
          0x00,
          0x61,
          0x73,
          0x6d,
          0x01,
          0x00,
          0x00,
          0x00,
        ]),
      );
      expect(component.sections.first.id, 0x01);
      expect(component.sections.first.payload, hasLength(8));
      expect(component.sections[1].id, 0x02);
      expect(component.sections[1].payload, hasLength(4));
    });

    test('decodes core-instance instantiate args', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance with arg_count=1
        0x02,
        0x05,
        0x01,
        0x00,
        0x00,
        0x01,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreInstances, hasLength(1));
      expect(component.coreInstances.single.moduleIndex, 0);
      expect(
        component.coreInstances.single.argumentInstanceIndices,
        orderedEquals(const <int>[0]),
      );
    });

    test('decodes core export aliases from section 0x03', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance declaration
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 3: one alias (instance0.foo -> apiFoo)
        0x03,
        0x0d,
        0x01,
        0x00,
        0x03,
        0x66,
        0x6f,
        0x6f,
        0x06,
        0x61,
        0x70,
        0x69,
        0x46,
        0x6f,
        0x6f,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreExportAliases, hasLength(1));
      expect(component.coreExportAliases.single.instanceIndex, 0);
      expect(component.coreExportAliases.single.coreExportName, 'foo');
      expect(component.coreExportAliases.single.componentExportName, 'apiFoo');
    });

    test('rejects duplicate component export aliases in section 0x03', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance declaration
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 3: two aliases with same component export name `dup`
        0x03,
        0x19,
        0x02,
        0x00,
        0x03,
        0x66,
        0x6f,
        0x6f,
        0x03,
        0x64,
        0x75,
        0x70,
        0x00,
        0x03,
        0x62,
        0x61,
        0x72,
        0x03,
        0x64,
        0x75,
        0x70,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes component import requirements from section 0x04', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 4: one function import requirement
        0x04,
        0x11,
        0x01,
        0x05,
        0x69,
        0x6e,
        0x63,
        0x46,
        0x6e,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.importRequirements, hasLength(1));
      final requirement = component.importRequirements.single;
      expect(requirement.componentImportName, 'incFn');
      expect(requirement.moduleName, 'host');
      expect(requirement.fieldName, 'inc');
      expect(requirement.kind, WasmComponentImportKind.function);
    });

    test('rejects duplicate component import names in section 0x04', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 4: two imports with same component import name `dup`
        0x04,
        0x1f,
        0x02,
        0x03,
        0x64,
        0x75,
        0x70,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x00,
        0x03,
        0x64,
        0x75,
        0x70,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x01,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes core instance aliases from section 0x05', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 5: one instance alias `main` -> 0
        0x05,
        0x07,
        0x01,
        0x04,
        0x6d,
        0x61,
        0x69,
        0x6e,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreInstanceAliases, hasLength(1));
      expect(component.coreInstanceAliases.single.aliasName, 'main');
      expect(component.coreInstanceAliases.single.instanceIndex, 0);
    });

    test('decodes component type declarations from section 0x06', () {
      final typeSection = <int>[
        ..._u32Leb(3),
        ..._name('i32_t'),
        0x00,
        0x7f,
        ..._name('identity'),
        0x01,
        ..._u32Leb(1),
        0x7f,
        ..._u32Leb(1),
        0x7f,
        ..._name('i32_alias'),
        0x02,
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.typeDeclarations, hasLength(3));
      expect(component.typeDeclarations[0].name, 'i32_t');
      expect(component.typeDeclarations[0].kind, WasmComponentTypeKind.value);
      expect(component.typeDeclarations[0].valueTypeCode, 0x7f);
      expect(component.typeDeclarations[0].valueTypeSignature, '7f');
      expect(
        component.typeDeclarations[1].kind,
        WasmComponentTypeKind.function,
      );
      expect(
        component.typeDeclarations[1].parameterTypeCodes,
        orderedEquals(const <int>[0x7f]),
      );
      expect(
        component.typeDeclarations[1].resultTypeCodes,
        orderedEquals(const <int>[0x7f]),
      );
      expect(component.typeDeclarations[2].kind, WasmComponentTypeKind.alias);
      expect(component.typeDeclarations[2].aliasTargetIndex, 0);
    });

    test(
      'decodes component table type declarations with multi-byte ref signatures',
      () {
        final typeSection = <int>[
          ..._u32Leb(1),
          ..._name('tab_typed'),
          0x04, // table
          0x63, // ref null
          0x00, // heap type = type index 0 (signed LEB33)
          0x01, // has max
          ..._u32Leb(1),
          ..._u32Leb(2),
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x06, typeSection),
        ]);

        final component = WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        );
        expect(component.typeDeclarations, hasLength(1));
        final declaration = component.typeDeclarations.single;
        expect(declaration.kind, WasmComponentTypeKind.table);
        expect(declaration.tableType, isNotNull);
        expect(declaration.tableType!.refTypeSignature, '6300');
        expect(declaration.tableType!.min, 1);
        expect(declaration.tableType!.max, 2);
      },
    );

    test(
      'decodes component value type declarations with multi-byte ref signatures',
      () {
        final typeSection = <int>[
          ..._u32Leb(1),
          ..._name('g_typed'),
          0x00, // value
          0x63, // ref null
          0x00, // heap type = type index 0 (signed LEB33)
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x06, typeSection),
        ]);

        final component = WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        );
        expect(component.typeDeclarations, hasLength(1));
        final declaration = component.typeDeclarations.single;
        expect(declaration.kind, WasmComponentTypeKind.value);
        expect(declaration.valueTypeCode, 0x63);
        expect(declaration.valueTypeSignature, '6300');
      },
    );

    test('rejects out-of-range type alias target in section 0x06', () {
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('bad_alias'),
        0x02,
        ..._u32Leb(1),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('rejects type alias cycles in section 0x06', () {
      final typeSection = <int>[
        ..._u32Leb(2),
        ..._name('a'),
        0x02,
        ..._u32Leb(1),
        ..._name('b'),
        0x02,
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes type bindings from section 0x07', () {
      final importSection = <int>[
        ..._u32Leb(1),
        ..._name('incFn'),
        ..._name('host'),
        ..._name('inc'),
        0x00,
      ];
      final instanceSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final exportAliasSection = <int>[
        ..._u32Leb(1),
        ..._u32Leb(0),
        ..._name('one'),
        ..._name('apiOne'),
      ];
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('fn_t'),
        0x01,
        ..._u32Leb(1),
        0x7f,
        ..._u32Leb(1),
        0x7f,
      ];
      final typeBindingSection = <int>[
        ..._u32Leb(2),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
        0x01,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x02, instanceSection),
        ..._section(0x03, exportAliasSection),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.typeBindings, hasLength(2));
      expect(
        component.typeBindings[0].targetKind,
        WasmComponentTypeBindingTargetKind.importRequirement,
      );
      expect(component.typeBindings[0].targetIndex, 0);
      expect(component.typeBindings[0].typeDeclarationIndex, 0);
      expect(
        component.typeBindings[1].targetKind,
        WasmComponentTypeBindingTargetKind.coreExportAlias,
      );
      expect(component.typeBindings[1].targetIndex, 0);
      expect(component.typeBindings[1].typeDeclarationIndex, 0);
    });

    test('decodes unknown type-binding target kinds as opaque entries', () {
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('fn_t'),
        0x01,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x40,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );
      expect(component.typeBindings, hasLength(1));
      expect(
        component.typeBindings.single.targetKind,
        WasmComponentTypeBindingTargetKind.opaque,
      );
      expect(component.typeBindings.single.rawTargetKind, 0x40);

      final bestEffort = WasmComponent.decodeBestEffort(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );
      expect(
        bestEffort.sections.where((section) => section.id == 0x07),
        hasLength(1),
      );
      expect(bestEffort.typeBindings, hasLength(1));
      expect(
        bestEffort.typeBindings.single.targetKind,
        WasmComponentTypeBindingTargetKind.opaque,
      );
      expect(bestEffort.typeDeclarations, hasLength(1));
    });

    test(
      'retains opaque type-binding entries when section has trailing bytes',
      () {
        final typeSection = <int>[
          ..._u32Leb(1),
          ..._name('fn_t'),
          0x01,
          ..._u32Leb(0),
          ..._u32Leb(0),
        ];
        final typeBindingSection = <int>[
          ..._u32Leb(1),
          0x40,
          ..._u32Leb(0),
          ..._u32Leb(0),
          0xff, // unknown trailing byte kept for forward-compat paths
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x06, typeSection),
          ..._section(0x07, typeBindingSection),
        ]);

        final component = WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        );
        expect(component.typeBindings, hasLength(1));
        expect(
          component.typeBindings.single.targetKind,
          WasmComponentTypeBindingTargetKind.opaque,
        );
      },
    );

    test(
      'decodeBestEffort skips malformed structured import sections with trailing bytes',
      () {
        final malformedImportSection = <int>[
          ..._u32Leb(0),
          0x00, // trailing byte
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x04, malformedImportSection),
        ]);

        expect(
          () => WasmComponent.decode(
            componentBytes,
            features: const WasmFeatureSet(componentModel: true),
          ),
          throwsFormatException,
        );

        final bestEffort = WasmComponent.decodeBestEffort(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        );
        expect(
          bestEffort.sections.where((section) => section.id == 0x04),
          hasLength(1),
        );
        expect(bestEffort.importRequirements, isEmpty);
      },
    );

    test(
      'rejects function import type binding to non-function declaration',
      () {
        final importSection = <int>[
          ..._u32Leb(1),
          ..._name('incFn'),
          ..._name('host'),
          ..._name('inc'),
          0x00,
        ];
        final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
        final typeBindingSection = <int>[
          ..._u32Leb(1),
          0x00,
          ..._u32Leb(0),
          ..._u32Leb(0),
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x04, importSection),
          ..._section(0x06, typeSection),
          ..._section(0x07, typeBindingSection),
        ]);

        expect(
          () => WasmComponent.decode(
            componentBytes,
            features: const WasmFeatureSet(componentModel: true),
          ),
          throwsFormatException,
        );
      },
    );

    test('accepts memory import type bindings at decode time', () {
      final importSection = <int>[
        ..._u32Leb(1),
        ..._name('mem'),
        ..._name('env'),
        ..._name('memory'),
        0x01,
      ];
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('mem_t'),
        0x03, // memory
        0x01, // has max
        ..._u32Leb(1), // min pages
        ..._u32Leb(2), // max pages
      ];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );
      expect(component.typeBindings, hasLength(1));
      expect(
        component.typeBindings.single.targetKind,
        WasmComponentTypeBindingTargetKind.importRequirement,
      );
      expect(component.typeBindings.single.targetIndex, 0);
      expect(component.typeBindings.single.typeDeclarationIndex, 0);
      expect(
        component.typeDeclarations.single.kind,
        WasmComponentTypeKind.memory,
      );
      expect(component.typeDeclarations.single.memoryType?.minPages, 1);
      expect(component.typeDeclarations.single.memoryType?.maxPages, 2);
    });

    test('accepts table/tag import type bindings at decode time', () {
      final importSection = <int>[
        ..._u32Leb(2),
        ..._name('tab'),
        ..._name('env'),
        ..._name('table'),
        0x02,
        ..._name('errTag'),
        ..._name('env'),
        ..._name('tag'),
        0x04,
      ];
      final typeSection = <int>[
        ..._u32Leb(2),
        ..._name('tab_t'),
        0x04, // table
        0x70, // funcref
        0x01, // has max
        ..._u32Leb(1), // min
        ..._u32Leb(2), // max
        ..._name('tag_t'),
        0x05, // tag
        ..._u32Leb(1), // param count
        0x7f, // i32
      ];
      final typeBindingSection = <int>[
        ..._u32Leb(2),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
        0x00,
        ..._u32Leb(1),
        ..._u32Leb(1),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );
      expect(component.typeBindings, hasLength(2));
      expect(component.typeBindings[0].targetIndex, 0);
      expect(component.typeBindings[1].targetIndex, 1);
      expect(component.typeDeclarations[0].kind, WasmComponentTypeKind.table);
      expect(component.typeDeclarations[1].kind, WasmComponentTypeKind.tag);
      expect(
        component.typeDeclarations[1].tagParameterTypeCodes,
        orderedEquals(const <int>[0x7f]),
      );
    });

    test('rejects memory import type binding to non-memory declaration', () {
      final importSection = <int>[
        ..._u32Leb(1),
        ..._name('mem'),
        ..._name('env'),
        ..._name('memory'),
        0x01,
      ];
      final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('rejects table import type binding to non-table declaration', () {
      final importSection = <int>[
        ..._u32Leb(1),
        ..._name('tab'),
        ..._name('env'),
        ..._name('table'),
        0x02,
      ];
      final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('rejects tag import type binding to non-tag declaration', () {
      final importSection = <int>[
        ..._u32Leb(1),
        ..._name('errTag'),
        ..._name('env'),
        ..._name('tag'),
        0x04,
      ];
      final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('rejects malformed component memory type declaration limits', () {
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('mem_t'),
        0x03, // memory
        0x01, // has max
        ..._u32Leb(3), // min
        ..._u32Leb(2), // max
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test(
      'rejects malformed shared component memory type declaration without max',
      () {
        final typeSection = <int>[
          ..._u32Leb(1),
          ..._name('mem_t'),
          0x03, // memory
          0x02, // shared without has-max
          ..._u32Leb(1), // min
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x06, typeSection),
        ]);

        expect(
          () => WasmComponent.decode(
            componentBytes,
            features: const WasmFeatureSet(componentModel: true),
          ),
          throwsFormatException,
        );
      },
    );

    test('rejects malformed component table type declaration limits', () {
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('tab_t'),
        0x04, // table
        0x70, // funcref
        0x01, // has max
        ..._u32Leb(4), // min
        ..._u32Leb(3), // max
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test(
      'accepts core export alias type binding to non-function declaration at decode time',
      () {
        final instanceSection = <int>[
          ..._u32Leb(1),
          0x00,
          ..._u32Leb(0),
          ..._u32Leb(0),
        ];
        final exportAliasSection = <int>[
          ..._u32Leb(1),
          ..._u32Leb(0),
          ..._name('one'),
          ..._name('apiOne'),
        ];
        final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
        final typeBindingSection = <int>[
          ..._u32Leb(1),
          0x01,
          ..._u32Leb(0),
          ..._u32Leb(0),
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x02, instanceSection),
          ..._section(0x03, exportAliasSection),
          ..._section(0x06, typeSection),
          ..._section(0x07, typeBindingSection),
        ]);

        final component = WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        );
        expect(component.typeBindings, hasLength(1));
        expect(
          component.typeDeclarations.single.kind,
          WasmComponentTypeKind.value,
        );
      },
    );

    test('rejects type bindings with out-of-range indexes', () {
      final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(1),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, <int>[
          ..._u32Leb(1),
          ..._name('x'),
          ..._name('m'),
          ..._name('n'),
          0x00,
        ]),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('rejects unsupported component version', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });
  });
}

List<int> _componentHeaderWithOneCoreModule() {
  return <int>[
    0x00,
    0x61,
    0x73,
    0x6d,
    0x0d,
    0x00,
    0x01,
    0x00,
    0x01,
    0x08,
    0x00,
    0x61,
    0x73,
    0x6d,
    0x01,
    0x00,
    0x00,
    0x00,
  ];
}

List<int> _section(int id, List<int> payload) => <int>[
  id,
  ..._u32Leb(payload.length),
  ...payload,
];

List<int> _name(String value) => <int>[
  ..._u32Leb(value.length),
  ...value.codeUnits,
];

List<int> _u32Leb(int value) {
  if (value < 0) {
    throw ArgumentError.value(value, 'value', 'must be >= 0');
  }
  final out = <int>[];
  var remaining = value;
  do {
    var byte = remaining & 0x7f;
    remaining >>= 7;
    if (remaining != 0) {
      byte |= 0x80;
    }
    out.add(byte);
  } while (remaining != 0);
  return out;
}
