import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:wasd/wasd.dart';

void main() {
  group('WasmComponent.decode', () {
    test('requires componentModel feature', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
      ]);

      expect(
        () => WasmComponent.decode(componentBytes),
        throwsA(isA<UnsupportedError>()),
      );
    });

    test('decodes a minimal component and exposes sections', () {
      // Generated by wasm-tools component encoder from `(module)`.
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.sections, hasLength(2));
      expect(component.coreModules, hasLength(1));
      expect(component.coreInstances, hasLength(1));
      expect(component.coreInstances.single.moduleIndex, 0);
      expect(
        component.coreModules.single,
        orderedEquals(const <int>[
          0x00,
          0x61,
          0x73,
          0x6d,
          0x01,
          0x00,
          0x00,
          0x00,
        ]),
      );
      expect(component.sections.first.id, 0x01);
      expect(component.sections.first.payload, hasLength(8));
      expect(component.sections[1].id, 0x02);
      expect(component.sections[1].payload, hasLength(4));
    });

    test('decodes core-instance instantiate args', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance with arg_count=1
        0x02,
        0x05,
        0x01,
        0x00,
        0x00,
        0x01,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreInstances, hasLength(1));
      expect(component.coreInstances.single.moduleIndex, 0);
      expect(
        component.coreInstances.single.argumentInstanceIndices,
        orderedEquals(const <int>[0]),
      );
    });

    test('decodes core export aliases from section 0x03', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance declaration
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 3: one alias (instance0.foo -> apiFoo)
        0x03,
        0x0d,
        0x01,
        0x00,
        0x03,
        0x66,
        0x6f,
        0x6f,
        0x06,
        0x61,
        0x70,
        0x69,
        0x46,
        0x6f,
        0x6f,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreExportAliases, hasLength(1));
      expect(component.coreExportAliases.single.instanceIndex, 0);
      expect(component.coreExportAliases.single.coreExportName, 'foo');
      expect(component.coreExportAliases.single.componentExportName, 'apiFoo');
    });

    test('rejects duplicate component export aliases in section 0x03', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance declaration
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 3: two aliases with same component export name `dup`
        0x03,
        0x19,
        0x02,
        0x00,
        0x03,
        0x66,
        0x6f,
        0x6f,
        0x03,
        0x64,
        0x75,
        0x70,
        0x00,
        0x03,
        0x62,
        0x61,
        0x72,
        0x03,
        0x64,
        0x75,
        0x70,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes component import requirements from section 0x04', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 4: one function import requirement
        0x04,
        0x11,
        0x01,
        0x05,
        0x69,
        0x6e,
        0x63,
        0x46,
        0x6e,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.importRequirements, hasLength(1));
      final requirement = component.importRequirements.single;
      expect(requirement.componentImportName, 'incFn');
      expect(requirement.moduleName, 'host');
      expect(requirement.fieldName, 'inc');
      expect(requirement.kind, WasmComponentImportKind.function);
    });

    test('rejects duplicate component import names in section 0x04', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 4: two imports with same component import name `dup`
        0x04,
        0x1f,
        0x02,
        0x03,
        0x64,
        0x75,
        0x70,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x00,
        0x03,
        0x64,
        0x75,
        0x70,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x01,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes core instance aliases from section 0x05', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 5: one instance alias `main` -> 0
        0x05,
        0x07,
        0x01,
        0x04,
        0x6d,
        0x61,
        0x69,
        0x6e,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreInstanceAliases, hasLength(1));
      expect(component.coreInstanceAliases.single.aliasName, 'main');
      expect(component.coreInstanceAliases.single.instanceIndex, 0);
    });

    test('decodes component type declarations from section 0x06', () {
      final typeSection = <int>[
        ..._u32Leb(3),
        ..._name('i32_t'),
        0x00,
        0x7f,
        ..._name('identity'),
        0x01,
        ..._u32Leb(1),
        0x7f,
        ..._u32Leb(1),
        0x7f,
        ..._name('i32_alias'),
        0x02,
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.typeDeclarations, hasLength(3));
      expect(component.typeDeclarations[0].name, 'i32_t');
      expect(component.typeDeclarations[0].kind, WasmComponentTypeKind.value);
      expect(component.typeDeclarations[0].valueTypeCode, 0x7f);
      expect(
        component.typeDeclarations[1].kind,
        WasmComponentTypeKind.function,
      );
      expect(
        component.typeDeclarations[1].parameterTypeCodes,
        orderedEquals(const <int>[0x7f]),
      );
      expect(
        component.typeDeclarations[1].resultTypeCodes,
        orderedEquals(const <int>[0x7f]),
      );
      expect(component.typeDeclarations[2].kind, WasmComponentTypeKind.alias);
      expect(component.typeDeclarations[2].aliasTargetIndex, 0);
    });

    test('rejects out-of-range type alias target in section 0x06', () {
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('bad_alias'),
        0x02,
        ..._u32Leb(1),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('rejects type alias cycles in section 0x06', () {
      final typeSection = <int>[
        ..._u32Leb(2),
        ..._name('a'),
        0x02,
        ..._u32Leb(1),
        ..._name('b'),
        0x02,
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x06, typeSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes type bindings from section 0x07', () {
      final importSection = <int>[
        ..._u32Leb(1),
        ..._name('incFn'),
        ..._name('host'),
        ..._name('inc'),
        0x00,
      ];
      final instanceSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final exportAliasSection = <int>[
        ..._u32Leb(1),
        ..._u32Leb(0),
        ..._name('one'),
        ..._name('apiOne'),
      ];
      final typeSection = <int>[
        ..._u32Leb(1),
        ..._name('fn_t'),
        0x01,
        ..._u32Leb(1),
        0x7f,
        ..._u32Leb(1),
        0x7f,
      ];
      final typeBindingSection = <int>[
        ..._u32Leb(2),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
        0x01,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x02, instanceSection),
        ..._section(0x03, exportAliasSection),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.typeBindings, hasLength(2));
      expect(
        component.typeBindings[0].targetKind,
        WasmComponentTypeBindingTargetKind.importRequirement,
      );
      expect(component.typeBindings[0].targetIndex, 0);
      expect(component.typeBindings[0].typeDeclarationIndex, 0);
      expect(
        component.typeBindings[1].targetKind,
        WasmComponentTypeBindingTargetKind.coreExportAlias,
      );
      expect(component.typeBindings[1].targetIndex, 0);
      expect(component.typeBindings[1].typeDeclarationIndex, 0);
    });

    test(
      'rejects function import type binding to non-function declaration',
      () {
        final importSection = <int>[
          ..._u32Leb(1),
          ..._name('incFn'),
          ..._name('host'),
          ..._name('inc'),
          0x00,
        ];
        final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
        final typeBindingSection = <int>[
          ..._u32Leb(1),
          0x00,
          ..._u32Leb(0),
          ..._u32Leb(0),
        ];
        final componentBytes = Uint8List.fromList(<int>[
          ..._componentHeaderWithOneCoreModule(),
          ..._section(0x04, importSection),
          ..._section(0x06, typeSection),
          ..._section(0x07, typeBindingSection),
        ]);

        expect(
          () => WasmComponent.decode(
            componentBytes,
            features: const WasmFeatureSet(componentModel: true),
          ),
          throwsFormatException,
        );
      },
    );

    test('rejects unsupported memory import type bindings', () {
      final importSection = <int>[
        ..._u32Leb(1),
        ..._name('mem'),
        ..._name('env'),
        ..._name('memory'),
        0x01,
      ];
      final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(0),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, importSection),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsA(isA<UnsupportedError>()),
      );
    });

    test('rejects type bindings with out-of-range indexes', () {
      final typeSection = <int>[..._u32Leb(1), ..._name('i32_t'), 0x00, 0x7f];
      final typeBindingSection = <int>[
        ..._u32Leb(1),
        0x00,
        ..._u32Leb(0),
        ..._u32Leb(1),
      ];
      final componentBytes = Uint8List.fromList(<int>[
        ..._componentHeaderWithOneCoreModule(),
        ..._section(0x04, <int>[
          ..._u32Leb(1),
          ..._name('x'),
          ..._name('m'),
          ..._name('n'),
          0x00,
        ]),
        ..._section(0x06, typeSection),
        ..._section(0x07, typeBindingSection),
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('rejects unsupported component version', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });
  });
}

List<int> _componentHeaderWithOneCoreModule() {
  return <int>[
    0x00,
    0x61,
    0x73,
    0x6d,
    0x0d,
    0x00,
    0x01,
    0x00,
    0x01,
    0x08,
    0x00,
    0x61,
    0x73,
    0x6d,
    0x01,
    0x00,
    0x00,
    0x00,
  ];
}

List<int> _section(int id, List<int> payload) => <int>[
  id,
  ..._u32Leb(payload.length),
  ...payload,
];

List<int> _name(String value) => <int>[
  ..._u32Leb(value.length),
  ...value.codeUnits,
];

List<int> _u32Leb(int value) {
  if (value < 0) {
    throw ArgumentError.value(value, 'value', 'must be >= 0');
  }
  final out = <int>[];
  var remaining = value;
  do {
    var byte = remaining & 0x7f;
    remaining >>= 7;
    if (remaining != 0) {
      byte |= 0x80;
    }
    out.add(byte);
  } while (remaining != 0);
  return out;
}
