import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:wasd/wasd.dart';

void main() {
  group('WasmComponent.decode', () {
    test('requires componentModel feature', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
      ]);

      expect(
        () => WasmComponent.decode(componentBytes),
        throwsA(isA<UnsupportedError>()),
      );
    });

    test('decodes a minimal component and exposes sections', () {
      // Generated by wasm-tools component encoder from `(module)`.
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.sections, hasLength(2));
      expect(component.coreModules, hasLength(1));
      expect(component.coreInstances, hasLength(1));
      expect(component.coreInstances.single.moduleIndex, 0);
      expect(
        component.coreModules.single,
        orderedEquals(const <int>[
          0x00,
          0x61,
          0x73,
          0x6d,
          0x01,
          0x00,
          0x00,
          0x00,
        ]),
      );
      expect(component.sections.first.id, 0x01);
      expect(component.sections.first.payload, hasLength(8));
      expect(component.sections[1].id, 0x02);
      expect(component.sections[1].payload, hasLength(4));
    });

    test('rejects unsupported core-instance instantiate args', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance with arg_count=1 (unsupported)
        0x02,
        0x05,
        0x01,
        0x00,
        0x00,
        0x01,
        0x00,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsA(isA<UnsupportedError>()),
      );
    });

    test('decodes core export aliases from section 0x03', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance declaration
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 3: one alias (instance0.foo -> apiFoo)
        0x03,
        0x0d,
        0x01,
        0x00,
        0x03,
        0x66,
        0x6f,
        0x6f,
        0x06,
        0x61,
        0x70,
        0x69,
        0x46,
        0x6f,
        0x6f,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreExportAliases, hasLength(1));
      expect(component.coreExportAliases.single.instanceIndex, 0);
      expect(component.coreExportAliases.single.coreExportName, 'foo');
      expect(component.coreExportAliases.single.componentExportName, 'apiFoo');
    });

    test('rejects duplicate component export aliases in section 0x03', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 2: one core instance declaration
        0x02,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 3: two aliases with same component export name `dup`
        0x03,
        0x19,
        0x02,
        0x00,
        0x03,
        0x66,
        0x6f,
        0x6f,
        0x03,
        0x64,
        0x75,
        0x70,
        0x00,
        0x03,
        0x62,
        0x61,
        0x72,
        0x03,
        0x64,
        0x75,
        0x70,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes component import requirements from section 0x04', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 4: one function import requirement
        0x04,
        0x11,
        0x01,
        0x05,
        0x69,
        0x6e,
        0x63,
        0x46,
        0x6e,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.importRequirements, hasLength(1));
      final requirement = component.importRequirements.single;
      expect(requirement.componentImportName, 'incFn');
      expect(requirement.moduleName, 'host');
      expect(requirement.fieldName, 'inc');
      expect(requirement.kind, WasmComponentImportKind.function);
    });

    test('rejects duplicate component import names in section 0x04', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 4: two imports with same component import name `dup`
        0x04,
        0x1f,
        0x02,
        0x03,
        0x64,
        0x75,
        0x70,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x00,
        0x03,
        0x64,
        0x75,
        0x70,
        0x04,
        0x68,
        0x6f,
        0x73,
        0x74,
        0x03,
        0x69,
        0x6e,
        0x63,
        0x01,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });

    test('decodes core instance aliases from section 0x05', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x0d,
        0x00,
        0x01,
        0x00,
        // section 1: one core module payload
        0x01,
        0x08,
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
        // section 5: one instance alias `main` -> 0
        0x05,
        0x07,
        0x01,
        0x04,
        0x6d,
        0x61,
        0x69,
        0x6e,
        0x00,
      ]);

      final component = WasmComponent.decode(
        componentBytes,
        features: const WasmFeatureSet(componentModel: true),
      );

      expect(component.coreInstanceAliases, hasLength(1));
      expect(component.coreInstanceAliases.single.aliasName, 'main');
      expect(component.coreInstanceAliases.single.instanceIndex, 0);
    });

    test('rejects unsupported component version', () {
      final componentBytes = Uint8List.fromList(<int>[
        0x00,
        0x61,
        0x73,
        0x6d,
        0x01,
        0x00,
        0x00,
        0x00,
      ]);

      expect(
        () => WasmComponent.decode(
          componentBytes,
          features: const WasmFeatureSet(componentModel: true),
        ),
        throwsFormatException,
      );
    });
  });
}
