// Generated from test/fixtures/host_globals/*.wat with wasm-tools 1.254.0.
import 'dart:convert';
import 'dart:typed_data';

Uint8List hostGlobalFixture(String name) => base64Decode(_fixtures[name]!);

const _fixtures = <String, String>{
  'name_collision':
      'AGFzbQEAAAABBQFgAAF/AhUCAWEEYjo6YwN/AARhOjpiAWMDfwADAwIAAAcSAgVmaXJzdAAABnNlY29uZAABCgsCBAAjAAsEACMBCw==',
  'name_boundary':
      'AGFzbQEAAAABBQFgAAF/AgsBAWEEYjo6YwN/AAMCAQAHBwEDZ2V0AAAKBgEEACMACw==',
  'alias':
      'AGFzbQEAAAABDANgAABgAAF/YAF/AAIqAwRob3N0BHRpY2sAAARob3N0BWZpcnN0A38BBGhvc3QGc2Vjb25kA38BAwQDAQICBgYBfwFBCQsHMQYFZmlyc3QDAAZzZWNvbmQDAQVvd25lZAMCA2dldAABA3NldAACCHNldE93bmVkAAMKGgMGABAAIwELCAAQACAAJAALCAAQACAAJAILACcEbmFtZQEHAQAEdGljawcXAwAFZmlyc3QBBnNlY29uZAIFb3duZWQ=',
  'f32_export_bits':
      'AGFzbQEAAAABBQFgAAF/AwIBAAYJAX0BQ0UjoX8LBxACBXZhbHVlAwAEYml0cwAACgcBBQAjALwLAA8EbmFtZQcIAQAFdmFsdWU=',
  'f32_immutable':
      'AGFzbQEAAAABCAJgAABgAAF9AhsCBGhvc3QEdGljawAABGhvc3QFdmFsdWUDfQADAgEBBw8CBXZhbHVlAwADZ2V0AAEKCAEGABAAIwALABgEbmFtZQEHAQAEdGljawcIAQAFdmFsdWU=',
  'f32_mutable':
      'AGFzbQEAAAABEARgAABgAAF9YAF9AGAAAX8CGwIEaG9zdAR0aWNrAAAEaG9zdAV2YWx1ZQN9AQMEAwECAwccBAV2YWx1ZQMAA2dldAABA3NldAACBGJpdHMAAwoZAwYAEAAjAAsIABAAIAAkAAsHABAAIwC8CwAYBG5hbWUBBwEABHRpY2sHCAEABXZhbHVl',
  'f64_export_bits':
      'AGFzbQEAAAABBQFgAAF+AwIBAAYNAXwBRLyaeFY0EvB/CwcQAgV2YWx1ZQMABGJpdHMAAAoHAQUAIwC9CwAPBG5hbWUHCAEABXZhbHVl',
  'f64_immutable':
      'AGFzbQEAAAABCAJgAABgAAF8AhsCBGhvc3QEdGljawAABGhvc3QFdmFsdWUDfAADAgEBBw8CBXZhbHVlAwADZ2V0AAEKCAEGABAAIwALABgEbmFtZQEHAQAEdGljawcIAQAFdmFsdWU=',
  'f64_mutable':
      'AGFzbQEAAAABEARgAABgAAF8YAF8AGAAAX4CGwIEaG9zdAR0aWNrAAAEaG9zdAV2YWx1ZQN8AQMEAwECAwccBAV2YWx1ZQMAA2dldAABA3NldAACBGJpdHMAAwoZAwYAEAAjAAsIABAAIAAkAAsHABAAIwC9CwAYBG5hbWUBBwEABHRpY2sHCAEABXZhbHVl',
  'i32_immutable':
      'AGFzbQEAAAABCAJgAABgAAF/AhsCBGhvc3QEdGljawAABGhvc3QFdmFsdWUDfwADAgEBBw8CBXZhbHVlAwADZ2V0AAEKCAEGABAAIwALABgEbmFtZQEHAQAEdGljawcIAQAFdmFsdWU=',
  'i32_mutable':
      'AGFzbQEAAAABDANgAABgAAF/YAF/AAIbAgRob3N0BHRpY2sAAARob3N0BXZhbHVlA38BAwMCAQIHFQMFdmFsdWUDAANnZXQAAQNzZXQAAgoRAgYAEAAjAAsIABAAIAAkAAsAGARuYW1lAQcBAAR0aWNrBwgBAAV2YWx1ZQ==',
  'i64_immutable':
      'AGFzbQEAAAABDANgAABgAAF+YAABfwIbAgRob3N0BHRpY2sAAARob3N0BXZhbHVlA34AAwQDAQICBx8EBXZhbHVlAwADZ2V0AAEFZ2V0TG8AAgVnZXRIaQADChsDBgAQACMACwcAEAAjAKcLCgAQACMAQiCIpwsAGARuYW1lAQcBAAR0aWNrBwgBAAV2YWx1ZQ==',
  'i64_mutable':
      'AGFzbQEAAAABFAVgAABgAAF+YAF+AGAAAX9gAX8AAhsCBGhvc3QEdGljawAABGhvc3QFdmFsdWUDfgEDBgUBAgMDBAcyBgV2YWx1ZQMAA2dldAABA3NldAACBWdldExvAAMFZ2V0SGkABApzZXRGcm9tSTMyAAUKLgUGABAAIwALCAAQACAAJAALBwAQACMApwsKABAAIwBCIIinCwkAEAAgAKwkAAsAGARuYW1lAQcBAAR0aWNrBwgBAAV2YWx1ZQ==',
  'ref_import': 'AGFzbQEAAAACDwEEaG9zdAV2YWx1ZQNvAA==',
  'start_effect':
      'AGFzbQEAAAABBAFgAAACLQMEaG9zdAV2YWx1ZQN/AQRob3N0B3N0YXJ0ZWQAAARob3N0Bm1lbW9yeQIAAQMCAQAIAQEKBgEEABAACwsHAQBBAAsBeAAYBG5hbWUBEQIAB3N0YXJ0ZWQBBXN0YXJ0',
};
