name: wasd_flutter_example
description: "Flutter DOOM example."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  wasd:
    path: ../../

flutter:
  uses-material-design: true
